workspace:
  #base: "/go/src/wgo"
  base: "/drone"
  path: "."

clone:
  git:
    image: plugins/git
    tags: true
    depth: 50

pipeline:
  publish:
    image: plugins/docker
    registry: ccr.ccs.tencentyun.com
    repo: ccr.ccs.tencentyun.com/phyzi/wgo
    secrets: [ docker_username, docker_password ]
    tags:
      - modules
      - ${DRONE_TAG}
    #auto_tag: true
    dockerfile: docker/Dockerfile
    when:
      branch: [refs/tags/*]
      event: [ tag ]

  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: dev
    username: "WGO"
    template: >
      {{#success build.status}}
      build {{build.number}} succeeded. Good job.
      {{else}}
      build {{build.number}} failed. Fix me please.
      {{/success}}
    when:
      status: [ success, failure ]
      local: false
